#!/bin/bash
# Railway Environment Setup for DeepSeek API

echo "🚀 TopNews Railway Configuration Helper"
echo "========================================="
echo ""
echo "To enable AI summaries in production, you need to:"
echo ""
echo "1️⃣  Get your DeepSeek API Key:"
echo "   - Visit: https://platform.deepseek.com/api_keys"
echo "   - Create a new API key if you don't have one"
echo "   - Copy the key (starts with 'sk-')"
echo ""
echo "2️⃣  Add to Railway Dashboard:"
echo "   - Open: https://railway.app/dashboard"
echo "   - Select your TopNews project"
echo "   - Click 'Variables' tab"
echo "   - Click 'New Variable'"
echo "   - Name: DEEPSEEK_API_KEY"
echo "   - Value: sk-xxxxxxxxxxxxxxxxxxxxx (paste your key)"
echo "   - Click 'Save'"
echo ""
echo "3️⃣  Railway will automatically redeploy"
echo "   - Wait 2-3 minutes"
echo "   - Test by requesting AI summary from a news story"
echo ""
echo "✅ After setup, AI summaries should work!"
echo ""
echo "Debug: To check if API key is set locally:"
echo "  echo \$DEEPSEEK_API_KEY"
echo ""
